// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AccountInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type Query struct {
}
